"""The storage contract, and the key generation that makes it safe.

Same inversion as the pose backend: a Protocol, two implementations, configuration picks one.
Nothing above this layer knows whether bytes landed on a disk or in a bucket.

Two rules carry most of the weight here, and both come straight out of the audit.

**Keys are generated here. A caller cannot supply one.** The original `/upload` did this::

    blob = bucket.blob(file.filename)  # raw client-supplied name
    blob.upload_from_file(file)

Unauthenticated user input used directly as a storage path — path traversal and arbitrary
overwrite in two lines (FINDINGS §5.1). `put` therefore takes bytes and a media type and
*returns* the key it chose. There is no parameter through which a caller could name an object,
so the vulnerability is not mitigated, it is unrepresentable.

**URLs are constructed, never stored.** A URL embeds a host, a scheme, an expiry and sometimes a
signature — all deployment facts with shorter lifetimes than the object they point at. Persisting
one means a hostname change silently invalidates every row in the database. `put` returns a key;
:meth:`StorageBackend.url_for` builds a URL from it on demand, and Epic E's tables store keys
only.
"""

from __future__ import annotations

import re
import uuid
from dataclasses import dataclass
from typing import Final, Protocol, runtime_checkable

from openposture_api.storage.errors import InvalidObjectKeyError, UnsupportedContentTypeError

__all__ = [
    "CONTENT_TYPE_SUFFIXES",
    "DEFAULT_PREFIX",
    "StorageBackend",
    "StoredObject",
    "generate_key",
    "validate_key",
]

CONTENT_TYPE_SUFFIXES: Final[dict[str, str]] = {
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/webp": ".webp",
}
"""The media types this application accepts, and the suffix each one gets.

The suffix is derived from the *media type*, never from the uploaded filename. A file called
`photo.jpg.php` cannot influence what this layer writes, because the filename never reaches it.

Shared with the upload endpoint in OP-42, so the allowlist is stated once. `image/jpg` is
deliberately absent — it is not a registered media type, and accepting a common misspelling here
would mean the endpoint's allowlist and this one disagree about what a valid request looks like.
"""

DEFAULT_PREFIX: Final = "analyses"

_PREFIX_PATTERN: Final = re.compile(r"^[a-z0-9][a-z0-9/_-]*$")
"""Prefixes are code-supplied, but validated anyway — the check costs nothing and the day
someone threads a variable into one is the day it stops being code-supplied."""

_KEY_PATTERN: Final = re.compile(r"^[a-z0-9][a-z0-9/._-]*$")
"""What a key may contain, stated positively.

An allowlist pattern rather than a list of forbidden sequences. Blocklists here are a losing
game: `..`, `%2e%2e`, backslashes, NUL bytes, unicode separators, and whatever the next
normalisation quirk turns out to be. Nothing outside this character set is ever generated, so
nothing outside it needs to be accepted.
"""


@dataclass(frozen=True, slots=True)
class StoredObject:
    """What `put` returns: where the bytes went and what they were.

    Frozen because it is a record of something that already happened. Notably **no URL** — see
    the module docstring. Size and content type are here because Epic E's `analyses` table wants
    them and re-reading the object to find out would be absurd.
    """

    key: str
    size: int
    content_type: str


def validate_key(key: str) -> str:
    """Return `key` unchanged, or refuse it.

    Called on the way *in* for every operation, including `get` and `delete` whose keys come back
    from the database rather than from a user. That is not redundant: it is the check that keeps
    a corrupted or hand-edited row from turning into a read outside the storage root, and it is
    cheap enough that skipping it buys nothing.
    """
    if not key:
        raise InvalidObjectKeyError("object key must not be empty")

    if len(key) > 512:
        raise InvalidObjectKeyError(f"object key is too long ({len(key)} characters, max 512)")

    if not _KEY_PATTERN.match(key):
        raise InvalidObjectKeyError(
            f"object key {key!r} contains characters this layer will not handle. Keys are "
            "generated by the storage layer and match a narrow allowlist; a key that does not "
            "match did not come from here."
        )

    # Checked separately from the pattern so the message can name the actual danger. `..` is
    # inside the allowed character set — it has to be, because keys carry suffixes — so the
    # pattern alone would pass `analyses/../../etc/passwd`.
    if ".." in key:
        raise InvalidObjectKeyError(
            f"object key {key!r} contains a parent-directory reference. This is the "
            "path-traversal shape the legacy /upload endpoint was vulnerable to (FINDINGS §5.1)."
        )

    if key.startswith("/") or key.endswith("/"):
        raise InvalidObjectKeyError(
            f"object key {key!r} must be a relative path to a single object, with no leading or "
            "trailing separator"
        )

    if "//" in key:
        raise InvalidObjectKeyError(f"object key {key!r} contains an empty path segment")

    return key


def generate_key(content_type: str, *, prefix: str = DEFAULT_PREFIX) -> str:
    """Invent an opaque key for a new object.

    A random UUID, not a hash of the content and not anything derived from the request. A
    content hash would deduplicate identical uploads — which sounds like a feature until two
    users upload the same photo and deleting one user's analysis removes the other's, or until
    the key itself becomes a way to test whether a given image is already stored.

    :raises UnsupportedContentTypeError: for a media type outside :data:`CONTENT_TYPE_SUFFIXES`.
    :raises InvalidObjectKeyError: for a malformed prefix.
    """
    suffix = CONTENT_TYPE_SUFFIXES.get(content_type)
    if suffix is None:
        supported = ", ".join(sorted(CONTENT_TYPE_SUFFIXES))
        raise UnsupportedContentTypeError(
            f"{content_type!r} is not a supported media type. Supported: {supported}."
        )

    if not _PREFIX_PATTERN.match(prefix) or ".." in prefix:
        raise InvalidObjectKeyError(f"storage prefix {prefix!r} is not a safe path segment")

    return f"{prefix}/{uuid.uuid4().hex}{suffix}"


@runtime_checkable
class StorageBackend(Protocol):
    """Somewhere bytes can be put and later retrieved by key."""

    @property
    def name(self) -> str:
        """Short stable identifier, for logs and the readiness payload."""
        ...

    def put(self, data: bytes, *, content_type: str, prefix: str = DEFAULT_PREFIX) -> StoredObject:
        """Store `data` under a key this layer chooses, and report where it went.

        There is deliberately no `key` parameter. See the module docstring.
        """
        ...

    def get(self, key: str) -> bytes:
        """Read an object back.

        :raises ObjectNotFoundError: if there is nothing at `key`.
        :raises InvalidObjectKeyError: if `key` is not one this layer would have generated.
        """
        ...

    def delete(self, key: str) -> None:
        """Remove an object, or do nothing if it was already gone.

        **Idempotent, matching S3.** `DeleteObject` succeeds on a key that does not exist, and
        making the local implementation raise instead would mean the contract depended on which
        backend was configured — so a retry after a timeout would fail on one and succeed on the
        other.
        """
        ...

    def exists(self, key: str) -> bool:
        """Whether anything is stored at `key`."""
        ...

    def url_for(self, key: str, *, expires_in: int | None = None) -> str:
        """Build a URL a client can fetch this object from.

        Constructed on demand and never persisted. `expires_in` is honoured by backends that can
        sign URLs and ignored by those that cannot, which is a real difference in guarantee
        between the two implementations — see :class:`~openposture_api.storage.local.
        LocalDiskStorage`.
        """
        ...
