"""Initial schema — the seven tables from OP-50.

Revision ID: f7a2c9d81b3e
Revises:
Create Date: 2026-07-29

Creates all seven tables from the E2 model definitions. The upgrade delegates to
`Base.metadata.create_all` so that every constraint, index and naming-convention token is
generated by the same code path that the models use — there is no manual transcription of column
types or constraint names that could silently diverge.

Downgrade is symmetric: `drop_all` on the same table list, which SQLAlchemy resolves in
reverse-dependency order automatically.

**Why not `op.create_table()`?** The column-level Enum types (`native_enum=False,
create_constraint=True`) generate CHECK constraints whose names are resolved by the MetaData
naming convention. Encoding them in `op.create_table()` calls would require duplicating the
resolved names by hand — one per Enum, one per named CheckConstraint — and that transcription is
exactly the kind of thing that silently diverges over time. Delegating to `Base.metadata` keeps
the migration and the drift-detection check consistent by construction: if they produce the same
schema, `alembic check` emits nothing.

The future migration pattern (adding columns, new tables) will use `op.add_column`,
`op.create_table`, etc. as normal. This approach is specific to the initial migration where the
full schema is produced at once.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "f7a2c9d81b3e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Creation order respects FK dependencies. SQLAlchemy's create_all resolves this automatically,
# but an explicit list also documents the intended dependency graph and prevents a future edit
# from accidentally including a table that does not belong in this migration.
_TABLES = [
    "users",
    "refresh_tokens",
    "sessions",
    "analyses",
    "keypoints",
    "metrics",
    "findings",
]


def upgrade() -> None:
    import openposture_api.db.models  # noqa: F401 — registers all tables with Base.metadata
    from openposture_api.db.base import Base

    Base.metadata.create_all(
        op.get_bind(),
        tables=[Base.metadata.tables[t] for t in _TABLES],
    )


def downgrade() -> None:
    import openposture_api.db.models  # noqa: F401
    from openposture_api.db.base import Base

    # drop_all resolves reverse-dependency order; the explicit list keeps us from touching any
    # table that was not created by this migration.
    Base.metadata.drop_all(
        op.get_bind(),
        tables=[Base.metadata.tables[t] for t in _TABLES],
    )
