/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List analyses newest first
         * @description Returns a cursor-paginated list of the authenticated user's analyses. Pass the `next_cursor` from a previous response as `cursor` to advance. `next_cursor` is `null` on the last page.
         */
        get: operations["list_analyses_api_v1_analyses_get"];
        put?: never;
        /**
         * Analyse posture in a photograph
         * @description Upload a lateral photograph and receive a posture report. A report that could not assess some metrics still returns 201 with those metrics listed under `quality.gaps` — abstention is an answer, not an error.
         */
        post: operations["create_analysis_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch one analysis
         * @description Returns the full analysis record including keypoints, metrics, and findings. Returns 404 whether the analysis does not exist or belongs to a different user — existence is not leaked.
         */
        get: operations["get_analysis_api_v1_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete one analysis
         * @description Hard-deletes the analysis and all its child rows. Returns 404 whether the analysis does not exist or belongs to a different user — the same 404-not-403 rule as the read endpoint.
         */
        delete: operations["delete_analysis_api_v1_analyses__analysis_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session on every device
         * @description Revoke the whole family and clear the cookie.
         *
         *     Always 204, even when the cookie is absent or unrecognised. Logging out is not a place to
         *     report that a token was already invalid — the caller wanted no session, and afterwards
         *     there is no session. Reporting the difference would turn logout into a token oracle.
         *
         *     The family, not just the presented token, because "log out" means the session is over. A
         *     rotation the client had already performed elsewhere must not survive it.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new access token
         * @description Rotate the refresh token and mint a new access token.
         *
         *     The presented token is always retired, whatever else happens. A refresh that returned a
         *     new token while leaving the old one usable would make rotation decorative.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and sign in
         * @description Register, then immediately issue a session — nobody wants to log in twice.
         *
         *     **This route does leak whether an address is registered**, via the 409, and that is a
         *     known gap rather than an oversight. Closing it means always returning 201 and sending a
         *     "somebody tried to register your address" email, and ADR-0003 records that this project
         *     has no outbound mail path. The alternative — a 201 that silently creates nothing — lies
         *     to legitimate users about whether they have an account, which is worse.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Whether the process is alive. Checks nothing external and never fails for an external reason.
         */
        get: operations["liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Whether this instance can serve traffic. Returns 503 when any registered subsystem is not ready.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisDetail
         * @description Full analysis record, returned by `GET /api/v1/analyses/{id}`.
         */
        AnalysisDetail: {
            /** Assessed */
            assessed: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Findings */
            findings: components["schemas"]["StoredFinding"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            image: components["schemas"]["ImageSize"];
            /** Inference Ms */
            inference_ms: number;
            /** Keypoints */
            keypoints: components["schemas"]["DetectedLandmark"][];
            /** Metrics */
            metrics: components["schemas"]["StoredMetric"][];
            /** Object Key */
            object_key: string;
            /** Overall Score */
            overall_score: number | null;
            /** Pose Backend */
            pose_backend: string;
            /** Pose Detected */
            pose_detected: boolean;
            /** Rules Version */
            rules_version: string;
            /** Schema Version */
            schema_version: string;
            /** Total */
            total: number;
        };
        /**
         * AnalysisListItem
         * @description One row in the history list — enough to render a thumbnail row, nothing more.
         */
        AnalysisListItem: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Object Key */
            object_key: string;
            /** Overall Score */
            overall_score: number | null;
            /** Pose Detected */
            pose_detected: boolean;
        };
        /**
         * AnalysisPage
         * @description One page of the analysis history list.
         */
        AnalysisPage: {
            /** Items */
            items: components["schemas"]["AnalysisListItem"][];
            /**
             * Next Cursor
             * @description Opaque cursor to pass as `cursor` on the next request. `null` when this is the last page.
             */
            next_cursor: string | null;
        };
        /**
         * AnalysisResponse
         * @description What `POST /api/v1/analyses` returns on success.
         */
        AnalysisResponse: {
            /**
             * Id
             * Format: uuid
             * @description The analysis's database ID. Use this to retrieve or delete the record later. A UUID rather than an integer so that the presence of adjacent IDs is not leaked — a sequential key at `/analyses/41` implies `/analyses/40` belongs to somebody.
             */
            id: string;
            /** @description The uploaded photograph's dimensions after EXIF rotation is applied — what the user actually sees. This is the authoritative size for a client; see the note on `PostureReportModel.image` for why the two can differ. */
            image: components["schemas"]["ImageSize"];
            /**
             * Landmarks
             * @description Every landmark the backend returned, for drawing a skeleton over the photo. Empty when no pose was detected. The overlay is drawn client-side from these — the server never writes an annotated image, which would cost a round trip, storage for a derived artifact, and a cache-invalidation question every time the rules change.
             */
            landmarks: components["schemas"]["DetectedLandmark"][];
            /**
             * Object Key
             * @description Where the uploaded image was stored. A key, never a URL — a URL embeds a host and an expiry, and persisting one means a hostname change invalidates it.
             */
            object_key: string;
            /** Pose Detected */
            pose_detected: boolean;
            /** @description `null` exactly when `pose_detected` is false. */
            report: components["schemas"]["PostureReportModel"] | null;
        };
        /** Body_create_analysis_api_v1_analyses_post */
        Body_create_analysis_api_v1_analyses_post: {
            /**
             * Image
             * @description The photograph to analyse.
             */
            image: string;
        };
        /**
         * CredentialsRequest
         * @description The body of `POST /auth/register` and `POST /auth/login`.
         *
         *     One model for both, because the two must validate identically. If registration accepted a
         *     password that login rejected, an account could be created and never used again.
         */
        CredentialsRequest: {
            /**
             * Email
             * Format: email
             * @description Address to register or sign in with. Compared case-insensitively.
             */
            email: string;
            /**
             * Password
             * @description At least 12 characters. Length is the only property checked — no character-class rule, which pushes people towards `Password1!` and away from a long passphrase.
             */
            password: string;
        };
        /**
         * DetectedLandmark
         * @description One measured point, in the form a client needs to draw it.
         *
         *     **Normalised to the image, not in pixels.** The frontend renders the photo at whatever size
         *     the viewport allows, so a pixel coordinate would be wrong the moment the layout changed. `x`
         *     and `y` are fractions of width and height, which stay correct under any scale — the same
         *     reasoning as the world-space metrics, applied to presentation.
         *
         *     World coordinates are deliberately absent: they are metres from the hip and mean nothing on
         *     a 2D canvas.
         */
        DetectedLandmark: {
            /** Name */
            name: string;
            /**
             * Presence
             * @description [0, 1] — confidence the point is in frame at all.
             */
            presence: number;
            /**
             * Status
             * @description How usable this point is. A client must render anything other than `ok` distinctly or not at all — drawing a guessed position as though it were measured is the confident-wrong-answer failure this project exists to remove.
             * @enum {string}
             */
            status: "ok" | "low_confidence" | "not_detected" | "out_of_frame";
            /**
             * Visibility
             * @description [0, 1] — confidence the point is not occluded.
             */
            visibility: number;
            /**
             * X
             * @description Fraction of image width. May fall outside [0, 1].
             */
            x: number;
            /**
             * Y
             * @description Fraction of image height, origin top-left.
             */
            y: number;
        };
        /**
         * Finding
         * @description Something the engine noticed, already worded for a person.
         */
        Finding: {
            /**
             * Code
             * @description Stable identifier. Branch on this, not on `message`.
             */
            code: string;
            /** Confidence */
            confidence: number;
            /** Message */
            message: string;
            /** Metric */
            metric: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "major" | "minor" | "info";
            /** Value */
            value: number;
        };
        /**
         * Gap
         * @description A metric that could not be assessed, and what stopped it.
         */
        Gap: {
            /** Detail */
            detail: string;
            /** Keypoints */
            keypoints: {
                [key: string]: "ok" | "low_confidence" | "not_detected" | "out_of_frame";
            };
            /** Metric */
            metric: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "insufficient_keypoints" | "low_confidence";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness. Deliberately has no field that could ever be false.
         */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Version
             * @description Version of the running service.
             */
            version: string;
        };
        /** ImageSize */
        ImageSize: {
            /** Height */
            height: number;
            /** Width */
            width: number;
        };
        /**
         * Metric
         * @description One measurement, or an honest absence of one.
         */
        Metric: {
            /** Confidence */
            confidence: number | null;
            /**
             * Detail
             * @description Phrased for display by the engine, not by the client.
             */
            detail: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "insufficient_keypoints" | "low_confidence";
            /** Unit */
            unit: string;
            /**
             * Value
             * @description `null` whenever `status` is not `ok`. Never a guess — that is the point.
             */
            value: number | null;
        };
        /**
         * PostureReportModel
         * @description One assessment of one photograph. Mirrors `PostureReport.to_dict()` exactly.
         */
        PostureReportModel: {
            /** Backend */
            backend: string;
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** @description The frame the *backend* measured, which is not always the frame that was uploaded. `FakePoseBackend` ignores the image entirely and reports its preset's own size, so this can differ from `AnalysisResponse.image` whenever the fake backend is in use. For anything to do with the uploaded photograph — scaling an overlay, for instance — use `AnalysisResponse.image`. */
            image: components["schemas"]["ImageSize"];
            /** Inference Ms */
            inference_ms: number;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["Metric"];
            };
            /**
             * Overall Score
             * @description 0 to 100, or `null` when nothing could be measured. Null rather than 0 or 100: both would be confident claims about a photograph the engine could not assess.
             */
            overall_score: number | null;
            quality: components["schemas"]["Quality"];
            /** Rules Version */
            rules_version: string;
            /** Schema Version */
            schema_version: string;
        };
        /**
         * Quality
         * @description How much of the body the engine could actually see.
         */
        Quality: {
            /** Assessed */
            assessed: number;
            /** Coverage */
            coverage: number;
            /** Gaps */
            gaps: components["schemas"]["Gap"][];
            /** Keypoints */
            keypoints: {
                [key: string]: "ok" | "low_confidence" | "not_detected" | "out_of_frame";
            };
            /** Total */
            total: number;
        };
        /**
         * Readiness
         * @description Aggregate readiness: ready only when every registered check is.
         */
        Readiness: {
            /**
             * Checks
             * @description One entry per registered subsystem, in registration order.
             */
            checks?: components["schemas"]["ReadinessCheck"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** Version */
            version: string;
        };
        /**
         * ReadinessCheck
         * @description One subsystem's answer.
         */
        ReadinessCheck: {
            /**
             * Detail
             * @description Why it is not ready. Omitted when it is.
             */
            detail?: string | null;
            /** Name */
            name: string;
            /** Ready */
            ready: boolean;
        };
        /**
         * StoredFinding
         * @description One finding row as it came out of the database.
         */
        StoredFinding: {
            /** Code */
            code: string;
            /** Confidence */
            confidence: number;
            /** Message */
            message: string;
            /** Metric */
            metric: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "major" | "minor" | "info";
            /** Value */
            value: number;
        };
        /**
         * StoredMetric
         * @description One metric row as it came out of the database.
         */
        StoredMetric: {
            /** Code */
            code: string;
            /** Confidence */
            confidence: number | null;
            /** Detail */
            detail: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "insufficient_keypoints" | "low_confidence";
            /** Unit */
            unit: string;
            /** Value */
            value: number | null;
        };
        /**
         * TokenResponse
         * @description What every successful auth route returns.
         *
         *     **The refresh token is deliberately not here.** It goes back as an `HttpOnly` cookie and
         *     appears in no response body anywhere, which is what makes "no token in `localStorage`"
         *     a property of the API rather than a rule the frontend has to keep remembering.
         */
        TokenResponse: {
            /**
             * Access Token
             * @description Bearer token. Hold in memory only; never persist it.
             */
            access_token: string;
            /**
             * Expires In
             * @description Seconds until the access token expires. Sent so the client can refresh *before* expiry rather than discovering it through a failed request.
             */
            expires_in: number;
            /**
             * Token Type
             * @description RFC 6750 scheme, so the client sends `Authorization: Bearer <token>`.
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_analyses_api_v1_analyses_get: {
        parameters: {
            query?: {
                /** @description Page size. */
                limit?: number;
                /** @description Opaque cursor from `next_cursor`. */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisPage"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_analysis_api_v1_analyses_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description The file could not be decoded. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Over the size limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Format not supported. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Inference or storage failed downstream. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Inference is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_analysis_api_v1_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisDetail"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Analysis not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_analysis_api_v1_analyses__analysis_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Analysis not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Credentials rejected. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description The refresh token is missing, expired, unknown or already used. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description That email is already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Password or email rejected. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
}
