/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyse posture in a photograph
         * @description Upload a lateral photograph and receive a posture report. A report that could not assess some metrics still returns 201 with those metrics listed under `quality.gaps` — abstention is an answer, not an error.
         */
        post: operations["create_analysis_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Whether the process is alive. Checks nothing external and never fails for an external reason.
         */
        get: operations["liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Whether this instance can serve traffic. Returns 503 when any registered subsystem is not ready.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisResponse
         * @description What `POST /api/v1/analyses` returns on success.
         */
        AnalysisResponse: {
            image: components["schemas"]["ImageSize"];
            /**
             * Object Key
             * @description Where the uploaded image was stored. A key, never a URL — a URL embeds a host and an expiry, and persisting one means a hostname change invalidates it.
             */
            object_key: string;
            /** Pose Detected */
            pose_detected: boolean;
            /** @description `null` exactly when `pose_detected` is false. */
            report: components["schemas"]["PostureReportModel"] | null;
        };
        /** Body_create_analysis_api_v1_analyses_post */
        Body_create_analysis_api_v1_analyses_post: {
            /**
             * Image
             * @description The photograph to analyse.
             */
            image: string;
        };
        /**
         * Finding
         * @description Something the engine noticed, already worded for a person.
         */
        Finding: {
            /**
             * Code
             * @description Stable identifier. Branch on this, not on `message`.
             */
            code: string;
            /** Confidence */
            confidence: number;
            /** Message */
            message: string;
            /** Metric */
            metric: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "major" | "minor" | "info";
            /** Value */
            value: number;
        };
        /**
         * Gap
         * @description A metric that could not be assessed, and what stopped it.
         */
        Gap: {
            /** Detail */
            detail: string;
            /** Keypoints */
            keypoints: {
                [key: string]: "ok" | "low_confidence" | "not_detected" | "out_of_frame";
            };
            /** Metric */
            metric: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "insufficient_keypoints" | "low_confidence";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness. Deliberately has no field that could ever be false.
         */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Version
             * @description Version of the running service.
             */
            version: string;
        };
        /** ImageSize */
        ImageSize: {
            /** Height */
            height: number;
            /** Width */
            width: number;
        };
        /**
         * Metric
         * @description One measurement, or an honest absence of one.
         */
        Metric: {
            /** Confidence */
            confidence: number | null;
            /**
             * Detail
             * @description Phrased for display by the engine, not by the client.
             */
            detail: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "insufficient_keypoints" | "low_confidence";
            /** Unit */
            unit: string;
            /**
             * Value
             * @description `null` whenever `status` is not `ok`. Never a guess — that is the point.
             */
            value: number | null;
        };
        /**
         * PostureReportModel
         * @description One assessment of one photograph. Mirrors `PostureReport.to_dict()` exactly.
         */
        PostureReportModel: {
            /** Backend */
            backend: string;
            /** Findings */
            findings: components["schemas"]["Finding"][];
            image: components["schemas"]["ImageSize"];
            /** Inference Ms */
            inference_ms: number;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["Metric"];
            };
            /**
             * Overall Score
             * @description 0 to 100, or `null` when nothing could be measured. Null rather than 0 or 100: both would be confident claims about a photograph the engine could not assess.
             */
            overall_score: number | null;
            quality: components["schemas"]["Quality"];
            /** Rules Version */
            rules_version: string;
            /** Schema Version */
            schema_version: string;
        };
        /**
         * Quality
         * @description How much of the body the engine could actually see.
         */
        Quality: {
            /** Assessed */
            assessed: number;
            /** Coverage */
            coverage: number;
            /** Gaps */
            gaps: components["schemas"]["Gap"][];
            /** Keypoints */
            keypoints: {
                [key: string]: "ok" | "low_confidence" | "not_detected" | "out_of_frame";
            };
            /** Total */
            total: number;
        };
        /**
         * Readiness
         * @description Aggregate readiness: ready only when every registered check is.
         */
        Readiness: {
            /**
             * Checks
             * @description One entry per registered subsystem, in registration order.
             */
            checks?: components["schemas"]["ReadinessCheck"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /** Version */
            version: string;
        };
        /**
         * ReadinessCheck
         * @description One subsystem's answer.
         */
        ReadinessCheck: {
            /**
             * Detail
             * @description Why it is not ready. Omitted when it is.
             */
            detail?: string | null;
            /** Name */
            name: string;
            /** Ready */
            ready: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_analysis_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_analysis_api_v1_analyses_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description The file could not be decoded. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Over the size limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Format not supported. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Inference or storage failed downstream. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Inference is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
}
